services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - translation_net

  translation-api:
    build:
      context: ./translation-api
      dockerfile: dockerfile
    container_name: translation-api
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./translation-api/prisma:/app-api/prisma
    networks:
      - translation_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  translation-worker:
    build:
      context: ./translation-worker
      dockerfile: dockerfile
    container_name: translation-worker
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - translation_net
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  translation_net:
    driver: bridge

volumes:
  translation_db: