# --- ESTÁGIO 1: Builder ---
FROM node:20-alpine AS builder

RUN apk update && apk upgrade

WORKDIR /app-worker

COPY package*.json ./
RUN npm install

COPY . .


# --- ESTÁGIO 2: Production ---
FROM node:20-alpine

RUN apk update && apk upgrade

WORKDIR /app-worker

COPY --from=builder /app-worker/node_modules ./node_modules

COPY --from=builder /app-worker/src ./src
COPY --from=builder /app-worker/src/server.js ./

USER node

CMD [ "node", "server.js" ]