# --- ESTÁGIO 1: Builder ---
FROM node:20-alpine AS builder

RUN apk update && apk upgrade

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .


# --- ESTÁGIO 2: Production ---
FROM node:20-alpine

RUN apk update && apk upgrade

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/src ./src
COPY --from=builder /app/worker.js ./

USER node

CMD [ "node", "worker.js" ]